In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
police_calls_2023 = pd.read_csv('Data/pd_calls_for_service_2023_datasd.csv')
police_calls_2022 = pd.read_csv('Data/pd_calls_for_service_2022_datasd.csv')
police_calls_2021 = pd.read_csv('Data/pd_calls_for_service_2021_datasd.csv')
police_calls_2020 = pd.read_csv('Data/pd_calls_for_service_2020_datasd.csv')

In [3]:
police_calls = pd.concat([police_calls_2023, police_calls_2022, police_calls_2021, police_calls_2020])
disp_codes = pd.read_csv('Data/pd_dispo_codes_datasd.csv')
beats = pd.read_csv('Data/pd_beat_codes_list_datasd.csv')
police_calls = police_calls.merge(disp_codes, left_on= 'disposition', right_on= 'dispo_code')
police_calls = police_calls.merge(beats)
police_calls = police_calls[['date_time', 'day_of_week', 'call_type', 'disposition', 'priority', 'description', 'neighborhood']]
police_calls = police_calls.sort_values(by = 'priority', ascending = False)

In [4]:
police_calls['day_of_week'].value_counts()

5    252924
6    250044
3    249125
4    248489
2    238467
7    232660
1    214375
Name: day_of_week, dtype: int64

In [5]:
police_calls

,date_time,day_of_week,call_type,disposition,priority,description,neighborhood
1588528,2020-12-18 16:05:59,6,530,R,9,REPORT,Cherokee Point
1067134,2021-06-05 13:26:54,7,10852R,R,9,REPORT,Bay Park
890896,2021-10-13 12:10:07,4,653M,K,9,NO REPORT REQUIRED,Fairmount Village
1067142,2021-06-14 14:05:29,2,488R,R,9,REPORT,Bay Park
1428628,2021-10-06 16:24:28,4,530,R,9,REPORT,Chollas Creek
...,...,...,...,...,...,...,...
1156618,2021-01-28 09:13:16,5,1183,R,0,REPORT,Golden Hill
870004,2021-02-01 07:11:31,2,245,R,0,REPORT,North Park
203142,2020-06-29 17:24:04,2,1183,K,0,NO REPORT REQUIRED,Pacific Beach
1315951,2022-05-06 15:27:11,6,11-8,K,0,NO REPORT REQUIRED,Teralta West
98443,2021-03-16 16:41:28,3,10852,K,0,NO REPORT REQUIRED,East Village